### ISSUE TITLE
Error in 

### ISSUE THREAD

**Issue by dg01d** [aaronpk/XRay#58]
Got the following error today in Xray:

```
2018/02/01 14:47:43 [error] 14667#0: *31076 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function p3k\XRay\Formats\mb_convert_encoding() in /usr/share/nginx/www/vendor/p3k/xray/lib/XRay/Formats/HTML.php:114
Stack trace:
#0 /usr/share/nginx/www/vendor/p3k/xray/lib/XRay/Formats/HTML.php(23): p3k\XRay\Formats\HTML::toHtmlEntities('<!DOCTYPE html>...')
#1 /usr/share/nginx/www/vendor/p3k/xray/lib/XRay/Parser.php(54): p3k\XRay\Formats\HTML::parse(Object(p3k\HTTP), '<!DOCTYPE html>...', 'http://www.alle...', Array)
#2 /usr/share/nginx/www/vendor/p3k/xray/lib/XRay.php(38): p3k\XRay\Parser->parse('<!DOCTYPE html>...', 'http://www.alle...', Array)
#3 /usr/share/nginx/www/helpers.php(148): p3k\XRay->parse('http://www.alle...')
#4 /usr/share/nginx/www/nanopub.php(548): xray_machine('http://www.alle...', 'www.allenpike.c...')
#5 {main}
  thrown in /usr/share/nginx/www/vendor/p3k/xray/lib/XRay/Formats/HTML.php on line 114" while reading response header from upstream
```

The call to xray is the same one I've being using successfully all along.
```
$xray = new p3k\XRay();
$url_parse = $xray->parse($url);
```
 The page I'm trying to parse is http://www.allenpike.com/2018/blockchain/
Any ideas?

**Comment by aaronpk** [comment]
Sounds like your server doesn't have the [mbstring extension](http://php.net/manual/en/book.mbstring.php) enabled. This hasn't changed in XRay, did anything on your server change? Should be a quick fix though, just need to install that extension.

**Comment by dg01d** [comment]
Thanks aaron, in the move to php7 I appear to have missed a few extensions
